# Generated by Django 5.2 on 2026-10-07 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_work_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliverycalendartask',
            new_name='Delivery_de_start_d_7a91ce_idx',
            old_name='Delivery_de_start_d8d0e1_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverycalendartask',
            new_name='Delivery_de_status_3d14cc_idx',
            old_name='Delivery_de_status_72d6c9_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryplan',
            new_name='Delivery_de_status_80dd97_idx',
            old_name='Delivery_de_status_0e5e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryplan',
            new_name='Delivery_de_bde_id_bb0805_idx',
            old_name='Delivery_de_bde_9a3f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryplan',
            new_name='Delivery_de_bdm_id_d02efd_idx',
            old_name='Delivery_de_bdm_6dca6e_idx',
        ),
        migrations.RenameIndex(
            model_name='workitem',
            new_name='Delivery_wo_status_eb9ce9_idx',
            old_name='Delivery_wo_status_9cbd8c_idx',
        ),
        migrations.RenameIndex(
            model_name='workitem',
            new_name='Delivery_wo_bdm_id_3d9111_idx',
            old_name='Delivery_wo_bdm_id_4d5f2e_idx',
        ),
        migrations.RenameIndex(
            model_name='workitem',
            new_name='Delivery_wo_project_1840df_idx',
            old_name='Delivery_wo_project_6d9a7c_idx',
        ),
        migrations.RenameIndex(
            model_name='workitem',
            new_name='Delivery_wo_departm_819e43_idx',
            old_name='Delivery_wo_depart_0a0c3b_idx',
        ),
        migrations.AlterField(
            model_name='packagetasktemplate',
            name='gif_url',
            field=models.URLField(blank=True, help_text='Optional animated GIF URL; icon is used when empty.'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
