# Generated by Django 5.2 on 2026-10-07 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_rename_delivery_de_start_d8d0e1_idx_delivery_de_start_d_7a91ce_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycalendartask',
            name='reminder_days_before',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum 1 day before start date.'),
        ),
        migrations.AddField(
            model_name='deliverycalendartask',
            name='reminder_enabled',
            field=models.BooleanField(default=False, help_text='Send a notification before this task starts.'),
        ),
        migrations.AddField(
            model_name='deliverycalendartask',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Internal: whether the reminder was already sent.'),
        ),
        migrations.AddIndex(
            model_name='deliverycalendartask',
            index=models.Index(fields=['reminder_enabled', 'reminder_sent'], name='Delivery_de_reminde_33fe7d_idx'),
        ),
    ]
