# Generated by Django 5.2 on 2026-09-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeadManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'due_at']},
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='LeadManager_stage_8f5f74_idx',
            old_name='LeadManager__stage_o_6e43f1_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='LeadManager_next_fo_0d5d2a_idx',
            old_name='LeadManager__next_fo_6d8c10_idx',
        ),
    ]
