# Generated by Django 5.2 on 2026-09-28 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadManager', '0002_alter_task_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('snoozed', 'Snoozed'), ('missed', 'Missed')], db_index=True, default='pending', max_length=20)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('in_followup', 'In Follow-up'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('disqualified', 'Disqualified')], max_length=30)),
                ('to_stage', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('in_followup', 'In Follow-up'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('disqualified', 'Disqualified')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the status change')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LostReasonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('budget', 'Budget Mismatch'), ('existing', 'Already has an agency'), ('in_house', 'In-house team'), ('trust', 'Lack of trust'), ('timing', 'Bad timing'), ('out_of_scope', 'Out of scope'), ('competitor', 'Went to competitor'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_deliverable', models.CharField(max_length=200)),
                ('target_delivery_date', models.DateField()),
                ('approved_quote', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_type', models.CharField(choices=[('onetime', 'One-time'), ('retainer', 'Monthly Retainer'), ('milestone', 'Milestone-based')], default='onetime', max_length=20)),
                ('scope_notes', models.TextField(blank=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted by Department'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ['name'], 'verbose_name': 'Lead Source', 'verbose_name_plural': 'Lead Sources'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('rejected', 'Rejected'), ('callback', 'Callback Requested'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('onetime', 'One-time'), ('retainer', 'Monthly Retainer'), ('milestone', 'Milestone-based')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_tier',
            field=models.CharField(blank=True, choices=[('small', 'Under 50K'), ('medium', '50K – 2L'), ('large', '2L – 10L'), ('enterprise', '10L+')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='One or more agency services the lead is interested in.', related_name='leads_m2m', to='LeadManager.service'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='icon',
            field=models.CharField(blank=True, help_text="CSS icon class for UI (e.g. 'bi bi-google', 'bi bi-meta')", max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web & App Development'), ('seo', 'Search Engine Optimization'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('media_production', 'Media Production'), ('social_branding', 'Social Media & Branding')], default='web_dev', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_fk', to='LeadManager.service'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('in_followup', 'In Follow-up'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=30),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='LeadManager_created_4eed72_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='services',
            field=models.ManyToManyField(related_name='departments', to='LeadManager.service'),
        ),
        migrations.AddField(
            model_name='followupschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followupschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followupschedule',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='LeadManager.lead'),
        ),
        migrations.AddField(
            model_name='leadstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatushistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='LeadManager.lead'),
        ),
        migrations.AddField(
            model_name='lostreasonlog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reasons', to='LeadManager.lead'),
        ),
        migrations.AddField(
            model_name='lostreasonlog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehandover',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehandover',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='LeadManager.department'),
        ),
        migrations.AddField(
            model_name='servicehandover',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='LeadManager.lead'),
        ),
        migrations.AddField(
            model_name='servicehandover',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='LeadManager.service'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['due_at', 'status'], name='LeadManager_due_at_99b1b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicehandover',
            unique_together={('lead', 'service', 'department')},
        ),
    ]
