# Generated by Django 5.2 on 2026-09-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadManager', '0005_seed_roles_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='Auto-create a Renewal reminder N days before this date.', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='renewal_reminder_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('call', 'Phone Call'), ('video', 'Video Call'), ('in_person', 'In-person')], default='video', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('location', models.CharField(blank=True, help_text='Physical address or video link', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='LeadManager.lead')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('billing_type', models.CharField(choices=[('onetime', 'One-time'), ('retainer', 'Monthly Retainer'), ('milestone', 'Milestone-based')], default='retainer', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('scope', models.TextField(blank=True, help_text='Detailed scope of work')),
                ('file', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='LeadManager.lead')),
                ('services', models.ManyToManyField(blank=True, related_name='proposals', to='LeadManager.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_type', models.CharField(choices=[('meeting', 'Meeting'), ('renewal', 'Contract Renewal'), ('followup', 'Lead Follow-up'), ('contract', 'Contract Milestone'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Notification Sent'), ('completed', 'Completed'), ('snoozed', 'Snoozed'), ('missed', 'Missed')], db_index=True, default='pending', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('related_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='LeadManager.lead')),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='LeadManager.meeting')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_at', 'status'], name='LeadManager_schedul_0bfdd4_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['due_at', 'status'], name='LeadManager_due_at_63df25_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_type', 'status'], name='LeadManager_reminde_171b59_idx'),
        ),
    ]
