# Generated by Django 5.2 on 2026-10-02 16:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LeadManager', '0006_deal_contract_start_deal_renewal_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('work_mode', models.CharField(choices=[('office', 'Office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='office', max_length=10)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('probation', 'Probation'), ('active', 'Active'), ('notice', 'Serving notice'), ('exited', 'Exited')], db_index=True, default='onboarding', max_length=20)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.localdate)),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=160)),
                ('shift_start', models.TimeField(default=datetime.time(9, 30))),
                ('shift_end', models.TimeField(default=datetime.time(18, 30))),
                ('grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('show_on_tv', models.BooleanField(default=True, help_text='Include on the TV performance display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='LeadManager.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='HR.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_proof', 'ID proof'), ('address_proof', 'Address proof'), ('education', 'Education certificate'), ('experience', 'Experience letter'), ('offer_letter', 'Offer letter'), ('contract', 'Signed contract'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='employee_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HR.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('documents', 'Documents'), ('setup', 'Accounts & equipment'), ('compliance', 'Policies & compliance'), ('orientation', 'Orientation & training'), ('attendance', 'Attendance')], default='documents', max_length=20)),
                ('responsible', models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('manager', 'Reporting manager'), ('it', 'IT / Admin')], default='employee', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('requires_upload', models.BooleanField(default=False)),
                ('auto_key', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='onboarding/%Y/%m/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='HR.employee')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave empty for the company-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='LeadManager.department')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('documents', 'Documents'), ('setup', 'Accounts & equipment'), ('compliance', 'Policies & compliance'), ('orientation', 'Orientation & training'), ('attendance', 'Attendance')], default='documents', max_length=20)),
                ('responsible', models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('manager', 'Reporting manager'), ('it', 'IT / Admin')], default='employee', max_length=20)),
                ('due_after_days', models.PositiveSmallIntegerField(default=3)),
                ('required', models.BooleanField(default=True)),
                ('requires_upload', models.BooleanField(default=False)),
                ('auto_key', models.CharField(blank=True, choices=[('', 'Manual'), ('face_enrollment', 'Auto: face enrollment completed')], max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='HR.onboardingtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
