# Generated by Django 5.2 on 2026-10-02 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0005_role_capabilities'),
        ('HR', '0002_default_onboarding_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='approver',
            field=models.CharField(choices=[('hr', 'HR'), ('manager', 'Reporting manager'), ('admin', 'Super Admin')], default='hr', max_length=10),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingtemplate',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Use this workflow for new joiners in this role. Role beats department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='Control.role'),
        ),
        migrations.AddField(
            model_name='onboardingtemplatetask',
            name='approver',
            field=models.CharField(choices=[('hr', 'HR'), ('manager', 'Reporting manager'), ('admin', 'Super Admin')], default='hr', max_length=10),
        ),
        migrations.AddField(
            model_name='onboardingtemplatetask',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Completion must be approved before it counts.'),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Awaiting approval'), ('done', 'Done'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10),
        ),
    ]
