# Generated by Django 5.2 on 2026-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='submission_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times the employee has submitted this task. Only HR can reset.'),
        ),
    ]
