# Generated by Django 5.2 on 2026-10-02 16:47

import Performance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0001_initial'),
        ('LeadManager', '0006_deal_contract_start_deal_renewal_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('auto_key', models.CharField(blank=True, choices=[('', 'Manual entry'), ('leads_created', 'Leads created'), ('leads_won', 'Leads won'), ('revenue_won', 'Revenue won'), ('activities_logged', 'CRM activities logged'), ('tasks_completed', 'Tasks completed'), ('tasks_on_time_pct', 'Tasks completed on time (%)'), ('followups_completed', 'Follow-ups completed'), ('handovers_accepted', 'Project handovers accepted'), ('attendance_rate', 'Attendance rate (%)'), ('punctuality_pct', 'Punctuality (%)')], help_text='Computed automatically from system data when set.', max_length=30)),
                ('unit', models.CharField(blank=True, help_text='e.g. %, ₹, pts', max_length=20)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('higher_is_better', models.BooleanField(default=True)),
                ('default_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Leave empty to apply to every department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='LeadManager.department')),
            ],
            options={
                'verbose_name': 'KPI',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TVDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token', models.CharField(default=Performance.models.new_token, editable=False, max_length=64, unique=True)),
                ('seconds_per_slide', models.PositiveSmallIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Show only this department. Empty shows everyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeadManager.department')),
            ],
            options={
                'verbose_name': 'TV display',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month.')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_entries', to='HR.employee')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Performance.kpi')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'kpi', 'month'), name='one_entry_per_kpi_month')],
            },
        ),
    ]
