# Generated by Django 5.2 on 2026-10-03 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_workflow_roles_approvals'),
        ('Performance', '0002_default_kpis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why the plan is needed (areas of concern).')),
                ('goals', models.TextField(help_text='Measurable goals and the support provided. One per line.')),
                ('start_date', models.DateField()),
                ('review_date', models.DateField(help_text='Date of the formal review.')),
                ('start_score', models.PositiveSmallIntegerField(blank=True, help_text='Performance score when the plan began.', null=True)),
                ('target_score', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('improved', 'Completed - improved'), ('extended', 'Extended'), ('failed', 'Closed - not improved'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('outcome', models.TextField(blank=True, help_text='Final outcome notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='HR.employee')),
            ],
            options={
                'verbose_name': 'performance improvement plan',
                'ordering': ['status', 'review_date'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Performance.improvementplan')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
