# Generated by Django 5.2 on 2026-10-03 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_workflow_roles_approvals'),
        ('Performance', '0003_improvement_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BDEConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_target', models.DecimalField(decimal_places=2, default=200000, max_digits=14)),
                ('slabs', models.PositiveSmallIntegerField(default=10)),
                ('red_max', models.PositiveSmallIntegerField(default=5, help_text='Slabs 1 to this number are Red.')),
                ('yellow_max', models.PositiveSmallIntegerField(default=8, help_text='Slabs above Red up to this number are Yellow; the rest are Green.')),
                ('red_pip_months', models.PositiveSmallIntegerField(default=2, help_text='Consecutive Red months that trigger a PIP.')),
                ('yellow_pip_months', models.PositiveSmallIntegerField(default=4, help_text='Consecutive Yellow months that trigger a PIP.')),
                ('window_months', models.PositiveSmallIntegerField(default=4, help_text='Completed months evaluated.')),
                ('appraisal_green_months', models.PositiveSmallIntegerField(default=3, help_text='Green months in the window that make an employee appraisal-eligible.')),
                ('appraisal_mixed_green', models.PositiveSmallIntegerField(default=2, help_text='Mixed rule: Green months needed ...')),
                ('appraisal_mixed_yellow', models.PositiveSmallIntegerField(default=2, help_text='... together with this many Yellow months.')),
                ('neutral_yellow', models.PositiveSmallIntegerField(default=3, help_text='Neutral rule: Yellow months ...')),
                ('neutral_green', models.PositiveSmallIntegerField(default=1, help_text='... together with this many Green months.')),
            ],
            options={
                'verbose_name': 'BDE performance settings',
            },
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips_managed', to='HR.employee'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='target_requirements',
            field=models.TextField(blank=True, help_text='Targets the employee must reach.'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='trigger_months',
            field=models.CharField(blank=True, help_text='Months that triggered the plan.', max_length=120),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='trigger_reason',
            field=models.CharField(blank=True, help_text='What triggered the plan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='improvementplan',
            name='goals',
            field=models.TextField(help_text='Improvement objectives and the support provided. One per line.'),
        ),
        migrations.AlterField(
            model_name='improvementplan',
            name='reason',
            field=models.TextField(help_text='Performance concerns.'),
        ),
        migrations.AlterField(
            model_name='improvementplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under review'), ('improved', 'Successfully completed'), ('extended', 'Extended'), ('failed', 'Unsuccessful'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='active', max_length=15),
        ),
        migrations.CreateModel(
            name='BDETarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_target', models.DecimalField(decimal_places=2, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bde_target', to='HR.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HR.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('history', models.CharField(blank=True, help_text='Month-by-month colours.', max_length=255)),
                ('avg_achievement', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('green_months', models.PositiveSmallIntegerField(default=0)),
                ('yellow_months', models.PositiveSmallIntegerField(default=0)),
                ('red_months', models.PositiveSmallIntegerField(default=0)),
                ('manager_comments', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('recommended_increment_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_promotion', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('deferred', 'Deferred'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='HR.employee')),
            ],
            options={
                'ordering': ['-period_end', 'employee'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_end'), name='one_appraisal_per_period')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month.')),
                ('target', models.DecimalField(decimal_places=2, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achievement_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('slab', models.PositiveSmallIntegerField(default=0, help_text='Slabs fully or partly filled (0 to configured slabs).')),
                ('colour', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='red', max_length=10)),
                ('colour_override', models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=10)),
                ('category', models.CharField(blank=True, help_text='Performance category label.', max_length=30)),
                ('status', models.CharField(choices=[('pip', 'PIP'), ('appraisal', 'Appraisal'), ('neutral', 'Neutral'), ('on_track', 'On Track'), ('insufficient', 'Insufficient Data')], default='insufficient', help_text='Overall status after this month.', max_length=15)),
                ('pip_status', models.CharField(blank=True, max_length=15)),
                ('appraisal_status', models.CharField(blank=True, max_length=15)),
                ('manager_remarks', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='The month has ended and was finalised by the monthly run.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performance', to='HR.employee')),
            ],
            options={
                'ordering': ['-month', 'employee'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='one_performance_per_month'), models.CheckConstraint(condition=models.Q(('revenue__gte', 0)), name='performance_revenue_non_negative'), models.CheckConstraint(condition=models.Q(('target__gt', 0)), name='performance_target_positive')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('first_red', 'First Red month'), ('pip_red', 'Consecutive Red months - PIP'), ('third_yellow', 'Third consecutive Yellow month'), ('pip_yellow', 'Consecutive Yellow months - PIP'), ('appraisal', 'Appraisal eligible'), ('target_hit', 'Target achieved'), ('target_exceeded', 'Target exceeded'), ('review_due', 'Monthly review due'), ('pip_review_due', 'PIP review due')], max_length=20)),
                ('month', models.DateField()),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_alerts', to='HR.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'kind', 'month'), name='one_alert_per_kind_month')],
            },
        ),
    ]
