# Generated by Django 5.2 on 2026-10-02 23:43

from django.db import migrations, models


# name: (level, crm, all_leads, team_leads, team_mgr, hr, privileged, super_admin)
FLAGS = {
    "super_admin": (1, 1, 1, 0, 1, 1, 1, 1),
    "management": (2, 1, 1, 0, 1, 1, 1, 0),
    "hr": (3, 0, 0, 0, 1, 1, 0, 0),
    "project_manager": (4, 1, 1, 0, 1, 0, 0, 0),
    "bd_manager": (4, 1, 1, 0, 1, 0, 0, 0),
    "bd_team_lead": (5, 1, 0, 1, 1, 0, 0, 0),
    "bd_executive": (6, 1, 0, 0, 0, 0, 0, 0),
    "digital_marketing": (7, 0, 0, 0, 0, 0, 0, 0),
    "graphic_designer": (7, 0, 0, 0, 0, 0, 0, 0),
    "videographer": (7, 0, 0, 0, 0, 0, 0, 0),
    "video_editor": (7, 0, 0, 0, 0, 0, 0, 0),
    "developer": (7, 0, 0, 0, 0, 0, 0, 0),
}
NAMES = ("level", "can_use_crm", "sees_all_leads", "sees_team_leads", "can_manage_team",
         "can_manage_hr", "is_privileged", "is_super_admin")


def set_flags(apps, schema_editor):
    Role = apps.get_model("Control", "Role")
    for name, values in FLAGS.items():
        data = {k: (v if k == "level" else bool(v)) for k, v in zip(NAMES, values)}
        Role.objects.filter(name=name).update(is_system=True, **data)
    Role.objects.filter(name="employee").update(level=99)


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0004_org_hierarchy_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level', 'label']},
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_hr',
            field=models.BooleanField(default=False, help_text='Employees, onboarding, attendance admin, KPIs, TV displays.', verbose_name='HR access'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_team',
            field=models.BooleanField(default=False, help_text='Team performance views and data entry.', verbose_name='Team manager'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_use_crm',
            field=models.BooleanField(default=False, verbose_name='Can use CRM'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_privileged',
            field=models.BooleanField(default=False, help_text='Only a Super Admin may assign this role.', verbose_name='Privileged'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Complete rights, including roles and workflows.', verbose_name='Super Admin'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Built-in role; cannot be deleted.'),
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveSmallIntegerField(default=100, help_text='Seniority for ordering. Lower numbers are more senior.'),
        ),
        migrations.AddField(
            model_name='role',
            name='sees_all_leads',
            field=models.BooleanField(default=False, verbose_name='Sees every lead'),
        ),
        migrations.AddField(
            model_name='role',
            name='sees_team_leads',
            field=models.BooleanField(default=False, help_text='Also sees leads owned by employees who report to this user.', verbose_name='Sees leads of direct reports'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.SlugField(help_text='Internal key, set once.', max_length=40, unique=True),
        ),
        migrations.RunPython(set_flags, migrations.RunPython.noop),
    ]
