# Generated by Django 5.2 on 2026-10-02 16:47

import Attendance.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enroll', 'Enrollment'), ('in', 'Check-in'), ('out', 'Check-out')], max_length=6)),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('face_score', models.FloatField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half day'), ('remote', 'Remote'), ('absent', 'Absent'), ('leave', 'On leave')], default='present', max_length=10)),
                ('in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('in_accuracy_m', models.FloatField(blank=True, null=True)),
                ('in_distance_m', models.FloatField(blank=True, null=True)),
                ('in_within_geofence', models.BooleanField(default=False)),
                ('in_face_score', models.FloatField(blank=True, null=True)),
                ('in_snapshot', models.ImageField(blank=True, null=True, storage=Attendance.storage.private_storage, upload_to='attendance/%Y/%m/')),
                ('out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_accuracy_m', models.FloatField(blank=True, null=True)),
                ('out_distance_m', models.FloatField(blank=True, null=True)),
                ('out_within_geofence', models.BooleanField(default=False)),
                ('out_face_score', models.FloatField(blank=True, null=True)),
                ('out_snapshot', models.ImageField(blank=True, null=True, storage=Attendance.storage.private_storage, upload_to='attendance/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('snapshot', models.ImageField(blank=True, null=True, storage=Attendance.storage.private_storage, upload_to='face_enrollment/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_m', models.PositiveIntegerField(default=150, help_text='Allowed distance from the point, in metres.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
