# Generated by Django 5.2 on 2026-10-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendance', '0001_initial'),
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceattempt',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to='HR.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='HR.employee'),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_templates', to='HR.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.officelocation'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='one_record_per_day'),
        ),
    ]
